---
name: Deploy to GitHub Pages
on:
  push: { branches: [master] }
  issues: { types: [opened, edited, closed, reopened] }
  issue_comment: { types: [created, edited, deleted] }
  discussion_comment: { types: [created] }
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
  issues: read
  discussions: read
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'discussion_comment' || github.event.issue.number != 1 }}
    steps:
      - uses: actions/checkout@v4
      - name: Build site
        uses: acg-q/userscript-console@ffd137cd20c780e1b582e752c8631e9dbe1cc31c
        with: { command: build, github-token: "${{ secrets.GITHUB_TOKEN }}" }
      - name: Stage site structure
        run: |
          set -euo pipefail
          mkdir _site
          mv dist/* _site/
          mkdir _site/dist
          find _site -maxdepth 1 -name '*.user.js' -exec mv -t _site/dist {} +
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with: { path: ./_site }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: { name: github-pages, url: "${{ steps.d.outputs.page_url }}" }
    steps:
      - id: d
        uses: actions/deploy-pages@v4
